import type { ScheduleSlot, NoteItem, ExamPaper } from './types';

export const initialSchedule: ScheduleSlot[] = [
  {
    id: 'sch-1',
    title: 'Atomic Structure & Electronic Configuration',
    date: '2026-10-05',
    startTime: '16:00',
    endTime: '18:00',
    joinLink: 'https://meet.google.com/abc-defg-hij',
    medium: 'Bi-lingual',
  },
  {
    id: 'sch-2',
    title: 'Chemical Bonding — Part 1',
    date: '2026-10-07',
    startTime: '16:00',
    endTime: '18:00',
    joinLink: 'https://zoom.us/j/1234567890',
    medium: 'English',
  },
  {
    id: 'sch-3',
    title: 'Periodicity & Periodic Trends',
    date: '2026-10-09',
    startTime: '17:00',
    endTime: '19:00',
    joinLink: 'https://meet.google.com/xyz-wxyz-rst',
    medium: 'Sinhala',
  },
  {
    id: 'sch-4',
    title: 'Hydrocarbons — Alkanes & Alkenes',
    date: '2026-10-12',
    startTime: '16:00',
    endTime: '18:00',
    joinLink: 'https://zoom.us/j/9876543210',
    medium: 'Bi-lingual',
  },
];

export const initialNotes: NoteItem[] = [
  {
    id: 'note-1',
    title: 'Atomic Structure Fundamentals',
    unitNumber: 1,
    description: 'Covers subatomic particles, isotopes, electronic configuration, and quantum numbers with worked examples.',
    fileName: 'atomic-structure-notes.pdf',
    fileUrl: 'https://example.com/notes/atomic-structure-notes.pdf',
    medium: 'English',
    uploadedAt: '2026-09-20',
  },
  {
    id: 'note-2',
    title: 'Chemical Bonding — Complete Guide',
    unitNumber: 2,
    description: 'Ionic, covalent, dative bonds, VSEPR theory, shapes of molecules, and intermolecular forces.',
    fileName: 'chemical-bonding-guide.pdf',
    fileUrl: 'https://example.com/notes/chemical-bonding-guide.pdf',
    medium: 'English',
    uploadedAt: '2026-09-22',
  },
  {
    id: 'note-3',
    title: 'Thermodynamics Notes (Sinhala Medium)',
    unitNumber: 3,
    description: 'Enthalpy, entropy, Gibbs free energy, and Hess law explained in Sinhala with diagrams.',
    fileName: 'thermodynamics-sinhala.pdf',
    fileUrl: 'https://example.com/notes/thermodynamics-sinhala.pdf',
    medium: 'Sinhala',
    uploadedAt: '2026-09-24',
  },
  {
    id: 'note-4',
    title: 'Periodic Table & Periodicity',
    unitNumber: 4,
    description: 'Trends in atomic radius, ionization energy, electronegativity, and detailed group analysis.',
    fileName: 'periodicity-notes.pdf',
    fileUrl: 'https://example.com/notes/periodicity-notes.pdf',
    medium: 'English',
    uploadedAt: '2026-09-18',
  },
  {
    id: 'note-5',
    title: 'Transition Metals & Coordination Chemistry',
    unitNumber: 5,
    description: 'd-block elements, oxidation states, complex ions, ligand types, and color of transition metal complexes.',
    fileName: 'transition-metals-notes.pdf',
    fileUrl: 'https://example.com/notes/transition-metals-notes.pdf',
    medium: 'English',
    uploadedAt: '2026-09-26',
  },
  {
    id: 'note-6',
    title: 'Group 2 Elements — Sinhala Medium',
    unitNumber: 6,
    description: 'Alkaline earth metals, their properties, reactions, and compounds in Sinhala language.',
    fileName: 'group-2-sinhala.pdf',
    fileUrl: 'https://example.com/notes/group-2-sinhala.pdf',
    medium: 'Sinhala',
    uploadedAt: '2026-09-28',
  },
  {
    id: 'note-7',
    title: 'Introduction to Organic Chemistry',
    unitNumber: 7,
    description: 'Functional groups, nomenclature (IUPAC), isomerism, and basic reaction mechanisms.',
    fileName: 'organic-intro-notes.pdf',
    fileUrl: 'https://example.com/notes/organic-intro-notes.pdf',
    medium: 'English',
    uploadedAt: '2026-09-15',
  },
  {
    id: 'note-8',
    title: 'Hydrocarbons — Alkanes, Alkenes, Alkynes',
    unitNumber: 8,
    description: 'Complete coverage of saturated and unsaturated hydrocarbons with reaction mechanisms.',
    fileName: 'hydrocarbons-notes.pdf',
    fileUrl: 'https://example.com/notes/hydrocarbons-notes.pdf',
    medium: 'Bi-lingual',
    uploadedAt: '2026-09-30',
  },
  {
    id: 'note-9',
    title: 'Organic Reaction Mechanisms (Sinhala)',
    unitNumber: 9,
    description: 'Substitution, addition, and elimination mechanisms explained step-by-step in Sinhala.',
    fileName: 'organic-mechanisms-sinhala.pdf',
    fileUrl: 'https://example.com/notes/organic-mechanisms-sinhala.pdf',
    medium: 'Sinhala',
    uploadedAt: '2026-10-01',
  },
];

export const initialPapers: ExamPaper[] = [
  {
    id: 'paper-1',
    paperType: 'Model Papers',
    title: 'Atomic Structure & Stoichiometry — Model Paper',
    paperUrl: 'https://example.com/papers/week1-model-paper.pdf',
    markingSchemeUrl: 'https://example.com/papers/week1-marking-scheme.pdf',
    medium: 'English',
    publishedAt: '2026-09-21',
  },
  {
    id: 'paper-2',
    paperType: 'Model Papers',
    title: 'Chemical Bonding & Molecular Structure — Model Paper',
    paperUrl: 'https://example.com/papers/week2-model-paper.pdf',
    markingSchemeUrl: 'https://example.com/papers/week2-marking-scheme.pdf',
    medium: 'English',
    publishedAt: '2026-09-28',
  },
  {
    id: 'paper-3',
    paperType: 'Past Papers',
    title: '2025 A/L Chemistry Paper — Sinhala Medium',
    paperUrl: 'https://example.com/papers/2025-al-sinhala-paper.pdf',
    markingSchemeUrl: 'https://example.com/papers/2025-al-sinhala-marking.pdf',
    medium: 'Sinhala',
    publishedAt: '2026-10-02',
  },
];
